dwarf: check resolution success before validating prototype
If we check the prototype without having checked that the
reference resolution succeeded, we can end up with a very
misleading message such as, for example:

  ERROR: test.c: wrong prototype for static function my_function
  original: void my_function(void)
  static:   void my_function(struct something *)

This is because we (have to) assume that empty data means "void".

Check for resolution success before validating the prototype
so we get a proper error message saying:

  usfstl static functions/variables: failed to resolve my_function
  program: .../dwarf.c:187: void usfstl_resolve_static_references(void): Assertion `all_resolved' failed.

Change-Id: I6f80000a3431ed3520930a00ce63938d8cd01319